language: python

python:
  - '2.6'
  - '2.7'

install:
  - mkdir ~/.pywikibot

  - touch ~/.pywikibot/user-config.py
  - echo "import os" >> ~/.pywikibot/user-config.py
  - echo "mylang = 'en'" >> ~/.pywikibot/user-config.py
  - echo "family = 'wikipedia'" >> ~/.pywikibot/user-config.py
  - echo "usernames['wikipedia']['en'] = 'Pywikibot-test'" >> ~/.pywikibot/user-config.py
  - echo "password_file = os.path.expanduser('~/.pywikibot/passwordfile')" >> ~/.pywikibot/user-config.py

  - touch ~/.pywikibot/passwordfile
  - echo "('Pywikibot-test', '"$USER_PASSWORD"')" > ~/.pywikibot/passwordfile

  - cd externals/httplib2
  - python setup.py install
  - cd ../..

script:
  - python setup.py test

env:
  global:
    # This is the encrypted password, which can only be decrypted by Travis itself
    # See http://about.travis-ci.org/docs/user/encryption-keys/
    # And http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
    # Command use to generate: travis encrypt USER_PASSWORD=<pwd> -r wikimedia/pywikibot-core
    - secure: kofInMlisiTBt9o/Ustc/vySlkKfxGzGCX2LwA1D2waym8sDTS0o5gMJ5LsrT/BUKwZbe1vLozPHqZrrkQvsdTml+DpZuotzdILs0m0f3BUoexEC6OON5IDljuxFyETrD1Ug44ih5Mc4lVFOdTcBzg501ZmswGwQrBvg/OyEFfE=

notifications:
  irc:
    channels:
      - "chat.freenode.net#pywikipediabot"
    on_success: change
    on_failure: always
